#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#
#SHORT_DESCRIPTION: This role installs BeeGFS server

prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    declare -A CLUSTERS
    source /sNow/snow-tools/etc/snow.conf
else
    error_msg  "The /sNow/snow-tools/etc/snow.conf is not available."
    error_exit "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f /sNow/snow-tools/share/common.sh ]]; then
    source /sNow/snow-tools/share/common.sh
    get_os_distro
    architecture_identification
fi

# beegfs-mgmtd beegfs-meta beegfs-storage beegfs-admon
BEEGFS_SERVER=$(gawk 'BEGIN{beegfs="FALSE"}{if($2 ~ /beegfs/){beegfs="TRUE"}}END{print beegfs}' $SNOW_TOOL/etc/domains.conf)
if [[ "$BEEGFS_SERVER" == "TRUE" ]]; then
    wget -q http://www.beegfs.io/release/beegfs_${BEEGFS_VERSION}/dists/beegfs-deb8.list -P ${prefix}/etc/apt/sources.list.d/
    wget -q http://www.beegfs.io/release/latest-stable/gpg/DEB-GPG-KEY-beegfs -O- | chroot ${prefix} /usr/bin/apt-key add -
    chroot ${prefix} /usr/bin/apt-get update 
    installDebianPackage ${prefix} beegfs-mgmtd beegfs-meta beegfs-storage beegfs-admon
    if [[ -e ${SNOW_CONF}/system_files/etc/beegfs ]]; then 
        # Transfer the existing file to the final destination
        mkdir -p ${prefix}/etc/beegfs
        cp -p ${SNOW_CONF}/system_files/etc/beegfs/* ${prefix}/etc/beegfs/
    else
        cp -pr ${prefix}/etc/beegfs ${SNOW_CONF}/system_files/etc/
    fi
fi
