#!/bin/sh
# Configure the new image for sNow! HPC suite
# Developed by NPCNow! www.hpcnow.com
# Jordi Blasco
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    echo "Installation problem"
fi


#
#  Update APT lists.
#
chroot ${prefix} /usr/bin/apt-get update
# DHCP

# PXE

# TFTPBOOT

# KickStart (RedHat Based)

# Preseed (Debian Based)
# https://www.debian-administration.org/article/708/Automating_the_Debian_installer_with_PXE_and_preseeding
chroot ${prefix} /usr/bin/apt-get install dnsmasq
mkdir -p ${prefix}/srv/tftp
wget http://ftp.debian.org/debian/dists/wheezy/main/installer-amd64/current/images/netboot/netboot.tar.gz -O ${prefix}/srv/tftp/netboot.tar.gz
cd ${prefix}/srv/tftp; tar zxf netboot.tar.gz ; rm netboot.tar.gz


# AutoYast (SuSE Based)

# System Imager (Cloning System)
# http://www.systemimager.org/download/
REPOFILE=systemimager.org.list
URL=http://download.systemimager.org/sources.list.d/$REPOFILE
cd /etc/apt/sources.list.d/
wget $URL -O ${prefix}/etc/apt/sources.list.d/$REPOFILE
wget http://systemimager.org/pub/brian@thefinleys.com.gpg.key -O ${prefix}/tmp/brian@thefinleys.com.gpg.key
chroot ${prefix} /usr/bin/apt-key add /tmp/brian@thefinleys.com.gpg.key
chroot ${prefix} /usr/bin/apt-get update
chroot ${prefix} /usr/bin/apt-get install systemimager-server simple-state-manager
   
# Kali Linux (Forensics)

# Clonezilla (Cloning System and Data Recovery)

wget http://cfengine.com/pub/gpg.key -O ${prefix}/tmp/gpg.key
chroot ${prefix} /usr/bin/apt-key add /tmp/gpg.key
/bin/echo "deb http://cfengine.com/pub/apt/packages stable main" > ${prefix}/etc/apt/sources.list.d/cfengine-community.list
chroot ${prefix} /usr/bin/apt-get update
chroot ${prefix} /usr/bin/apt-get install cfengine-community
cp -p /sNow/snow-configspace/files/etc/init.d/firstboot ${prefix}/etc/init.d/firstboot
chroot ${prefix} /usr/sbin/update-rc.d firstboot defaults

#
#  Install the packages
#
installDebianPackage ${prefix} ipmitool 
