#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#

prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    . /sNow/snow-tools/etc/snow.conf
else
    echo "The /sNow/snow-tools/etc/snow.conf is not available."
    echo "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
    exit 1
fi

#  Update APT lists.
#chroot ${prefix} /usr/bin/apt-get update

# DMZ NIC setup
echo "

# The secondary network interface
allow-hotplug eth1
auto eth1
#iface eth1 inet dhcp
iface eth1 inet static
        address $IP_NIC2
        netmask $MASK_NIC2
        network $NET_NIC2
        broadcast $BC_NIC2
        gateway $GW_NIC2

" >> ${prefix}/etc/network/interfaces

#  Install the packages
#installDebianPackage ${prefix} 
 
