#!/bin/sh
# Configure the new image for sNow! HPC suite
# Developed by NPCNow! www.hpcnow.com
# Jordi Blasco
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi


#
#  Update APT lists.
#
#chroot ${prefix} /usr/bin/apt-get update

# DMZ NIC setup
echo "

# The secondary network interface
allow-hotplug eth1
auto eth1
#iface eth1 inet dhcp
iface eth1 inet static
        address $IP_NIC2
        netmask $MASK_NIC2
        network $NET_NIC2
        broadcast $BC_NIC2
        gateway $GW_NIC2

" >> ${prefix}/etc/network/interfaces

#
#  Install the packages
#
#installDebianPackage ${prefix} 
 
