#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#
#SHORT_DESCRIPTION: [DEPRECATED] Installs FAI for cluster provisioning
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    source /sNow/snow-tools/etc/snow.conf
else
    error_msg  "The /sNow/snow-tools/etc/snow.conf is not available."
    error_exit "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f /sNow/snow-tools/share/common.sh ]]; then
    source /sNow/snow-tools/share/common.sh
    get_os_distro
    architecture_identification
fi

# Log our start
logMessage Script $0 starting


#  Install FAI
installDebianPackage ${prefix} fai-client
installDebianPackage ${prefix} fai-doc
installDebianPackage ${prefix} fai-quickstart
installDebianPackage ${prefix} fai-server


#  Make sure sshd isn't running, this will cause our unmounting of the
# disk image to fail..
chroot ${prefix} /etc/init.d/fai-server stop

#
# Clone the public GIT repo from sNow (HPCNow!)
mkdir ${prefix}/srv/fai/config
cd ${prefix}/srv/fai/config
git clone ssh://git@bitbucket.org:hpcnow/snow-configspace.git
cd - 

#  Log our finish
logMessage Script $0 finished
