#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#
# Based on Steve Kemp's role: http://www.steve.org.uk/
#
#SHORT_DESCRIPTION: Installs GDM with VNC support.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    declare -A CLUSTERS
    source /sNow/snow-tools/etc/snow.conf
else
    error_msg  "The /sNow/snow-tools/etc/snow.conf is not available."
    error_exit "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f /sNow/snow-tools/share/common.sh ]]; then
    source /sNow/snow-tools/share/common.sh
    get_os_distro
    architecture_identification
fi

#  Update APT lists.
chroot ${prefix} /usr/bin/apt-get update

#  Install the packages
installDebianPackage ${prefix} xserver-xorg
installDebianPackage ${prefix} openbsd-inetd
installDebianPackage ${prefix} vnc4server
installDebianPackage ${prefix} xfonts-100dpi
installDebianPackage ${prefix} xfonts-75dpi
installDebianPackage ${prefix} xfonts-base
installDebianPackage ${prefix} rxvt
installDebianPackage ${prefix} gdm3
installDebianPackage ${prefix} lxde-core

# Add a new section to the GDM3 configuration file and setup inetd.conf
replace_text ${prefix}/etc/gdm3/daemon.conf "[xdmcp]" "[xdmcp]\n Enable=true"
replace_text ${prefix}/etc/inetd.conf "5900" "5900  stream  tcp  nowait  nobody.tty  /usr/bin/Xvnc Xvnc -inetd -query localhost -once -geometry 1024x768 -depth 16 securitytypes=none"
