#!/bin/sh
# Configure the new image for sNow! HPC suite
# Developed by NPCNow! www.hpcnow.com
# Jordi Blasco
#

prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi


#  Update APT lists.
chroot ${prefix} /usr/bin/apt-get update
# LDAP Install references : 
# https://wiki.debian.org/LDAP/OpenLDAPSetup
# http://www.server-world.info/en/note?os=Debian_8&p=openldap
# http://www.server-world.info/en/note?os=Debian_8&p=ssl
installDebianPackage ${prefix} slapd ldap-utils ldapscripts

#  Install the packages
