#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#

prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    . /sNow/snow-tools/etc/snow.conf
else
    echo "The /sNow/snow-tools/etc/snow.conf is not available."
    echo "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
    exit 1
fi

#  Update APT lists.
#chroot ${prefix} /usr/bin/apt-get update
# LDAP Install references : 
# https://wiki.debian.org/LDAP/OpenLDAPSetup
# http://www.server-world.info/en/note?os=Debian_8&p=openldap
# http://www.server-world.info/en/note?os=Debian_8&p=ssl
installDebianPackage ${prefix} slapd ldap-utils ldapscripts

#
#  Install the packages
#
