#!/bin/bash
#
# This file contains recipes to deploy domains using sNow! CLI
# Copyright (C) 2008 Jordi Blasco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# sNow! Cluster Suite is an opensource project developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website: www.hpcnow.com/snow
#
#SHORT_DESCRIPTION: Installs login node with workload manager clients and creates a new SSH instance allocated in 22022/TCP dedicated to end users.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    declare -A CLUSTERS
    source /sNow/snow-tools/etc/snow.conf
else
    error_msg  "The /sNow/snow-tools/etc/snow.conf is not available."
    error_exit "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f /sNow/snow-tools/share/common.sh ]]; then
    source /sNow/snow-tools/share/common.sh
    get_os_distro
    architecture_identification
fi

# Slurm Client Setup
if [[ -e $SNOW_CONF/system_files/etc/slurm/slurm.conf ]]; then
    chroot ${prefix} /usr/bin/apt-get update -q 
    installDebianPackage ${prefix} curl pbzip2 slurm-llnl slurm-client
    chroot ${prefix} /bin/systemctl enable munge.service
    # Check UIDs and GIDs
    if [[ "$(chroot ${prefix} id -u munge)" != "$MUNGE_UID"  &&  "$(chroot ${prefix} id -g munge)" != "$MUNGE_GID" ]]; then
        chroot ${prefix} /usr/sbin/groupmod -g $MUNGE_GID munge
        chroot ${prefix} /usr/sbin/usermod -u $MUNGE_UID -g $MUNGE_GID munge
    fi
    if [[ "$(chroot ${prefix} id -u slurm)" != "$SLURM_UID"  &&  "$(chroot ${prefix} id -g slurm)" != "$SLURM_GID" ]]; then
        chroot ${prefix} /usr/sbin/groupmod -g $SLURM_GID slurm
        chroot ${prefix} /usr/sbin/usermod -u $SLURM_UID -g $SLURM_GID slurm
    fi
    # Setup Munge key and Slurm
    cp -p $SNOW_CONF/system_files/etc/munge/munge.key ${prefix}/etc/munge/munge.key
    chroot ${prefix} /bin/mkdir -p /var/log/munge /var/lib/munge /etc/munge /var/run/munge
    chroot ${prefix} /bin/chown -R munge:munge /var/log/munge /var/lib/munge /etc/munge /var/run/munge
    chroot ${prefix} /bin/chmod 700 /etc/munge
    chroot ${prefix} /bin/chmod 600 /etc/munge/munge.key 
    chroot ${prefix} /bin/chown -R munge:munge /etc/munge
    cp -pr $SNOW_CONF/system_files/etc/slurm ${prefix}/etc/
    chroot ${prefix} /bin/mkdir -p /var/run/slurm /var/spool/slurmd /var/spool/slurm /var/log/slurm
    chroot ${prefix} /bin/chown -R slurm:slurm /etc/slurm /var/spool/slurmd /var/spool/slurm /var/log/slurm
    # Transfer Slurm user scripts
    ln -sf $SNOW_TOOL/etc/config_template.d/slurm_client/interactive ${SNOW_TOOL}/bin/
    ln -sf $SNOW_TOOL/etc/config_template.d/slurm_client/eb_wrap ${SNOW_TOOL}/bin/
    #ln -sf $SNOW_TOOL/etc/config_template.d/slurm_client/slurm_share_tree.sh ${SNOW_TOOL}/bin/
    if [[ ! -e $SNOW_CONF/system_files/etc/profile.d/slurm-source.sh ]]; then
        cp -p $SNOW_TOOL/etc/config_template.d/slurm_client/slurm-source.* $SNOW_CONF/system_files/etc/profile.d/
    fi
    ln -sf $SNOW_CONF/system_files/etc/profile.d/slurm-source.* ${prefix}/etc/profile.d/
    # Transfer slurm default environment for interactive usage
    if [[ ! -e $SNOW_CONF/system_files/etc/slurm.env ]]; then
        cp -p $SNOW_TOOL/etc/config_template.d/slurm_client/slurm.env $SNOW_CONF/system_files/etc/
    fi
    ln -sf $SNOW_CONF/system_files/etc/slurm.env $SNOW_TOOL/etc/slurm.env
fi

ln -sf ${SNOW_TOOL}/bin/snow-source.sh ${prefix}/etc/profile.d/snow.sh

# SSH Setup
if [[ -e /sNow/snow-configspace/system_files/etc/ssh/sshd_config.pub ]]; then 
    cp -p /sNow/snow-configspace/system_files/etc/ssh/sshd_config.pub ${prefix}/etc/ssh/sshd_config.pub
else
    cp -p ${prefix}/etc/ssh/sshd_config ${prefix}/etc/ssh/sshd_config.pub
    echo "UseDNS no" >> ${prefix}/etc/ssh/sshd_config.pub
    sed -i 's|Port 22$|Port 22022|g' ${prefix}/etc/ssh/sshd_config.pub
    sed -i 's|PermitRootLogin without-password|PermitRootLogin no|g' ${prefix}/etc/ssh/sshd_config.pub
    sed -i 's|^AllowUsers|#AllowUsers|g' ${prefix}/etc/ssh/sshd_config.pub
    sed -i 's|^AllowGroups|#AllowGroups|g' ${prefix}/etc/ssh/sshd_config.pub
    cp -p ${prefix}/etc/ssh/sshd_config.pub /sNow/snow-configspace/system_files/etc/ssh/sshd_config.pub
fi
cp -p ${prefix}/etc/systemd/system/sshd.service ${prefix}/etc/systemd/system/sshd_pub.service
sed -i 's|ExecStart=/usr/sbin/sshd -D $SSHD_OPTS|ExecStart=/usr/sbin/sshd -D $SSHD_OPTS -f /etc/ssh/sshd_config.pub|g' ${prefix}/etc/systemd/system/sshd_pub.service 
chroot ${prefix} /bin/systemctl enable sshd_pub.service

# Create a home directory for new users
cat <<EOF > ${prefix}/usr/share/pam-configs/mkhomedir
Name: Create home directory during login
Default: yes
Priority: 0
Session-Interactive-Only: yes
Session-Type: Additional
Session-Final:
       optional        pam_mkhomedir.so skel=/etc/skel/ umask=0002
EOF

chroot ${prefix} /usr/sbin/dpkg-reconfigure -f noninteractive libpam-runtime 2>&1



