#!/bin/sh
#
#  Configure the new image to be a minimal image, by removing
# packages I don't care about - and installing new ones I prefer.
#
# Steve
# --
# http://www.steve.org.uk/
#
#SHORT_DESCRIPTION: Installs a minimal OS.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    source /sNow/snow-tools/etc/snow.conf
else
    error_msg  "The /sNow/snow-tools/etc/snow.conf is not available."
    error_exit "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f /sNow/snow-tools/share/common.sh ]]; then
    source /sNow/snow-tools/share/common.sh
    get_os_distro
    architecture_identification
fi

#  Install some new packages - do this first to avoid dependency errors.
installDebianPackage ${prefix} syslog-ng 
installDebianPackage ${prefix} deborphan
installDebianPackage ${prefix} less
installDebianPackage ${prefix} screen
installDebianPackage ${prefix} sudo
installDebianPackage ${prefix} vim

#  Remove some standard packages.

# PPP stuff.
removeDebianPackage ${prefix} pppconfig
removeDebianPackage ${prefix} pppoeconf
removeDebianPackage ${prefix} pppoe
removeDebianPackage ${prefix} ppp
removeDebianPackage ${prefix} libpcap0.7

# Editors
removeDebianPackage ${prefix} nano
removeDebianPackage ${prefix} ed
removeDebianPackage ${prefix} nvi

# Syslog
removeDebianPackage ${prefix} klogd
removeDebianPackage ${prefix} sysklogd

# manpages
removeDebianPackage ${prefix} manpages  
removeDebianPackage ${prefix} man-db 
removeDebianPackage ${prefix} info

# misc
removeDebianPackage ${prefix} tasksel tasksel-data
removeDebianPackage ${prefix} pciutils
removeDebianPackage ${prefix} fdutils
removeDebianPackage ${prefix} cpio
