#!/bin/bash
#
# This file contains recipes to deploy domains using sNow! CLI
# Copyright (C) 2008 Jordi Blasco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# sNow! Cluster Suite is an opensource project developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website: www.hpcnow.com/snow
#
# Based on Steve Kemp's role: http://www.steve.org.uk/
#
#SHORT_DESCRIPTION: Installs a minimal OS.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e ${SNOW_ETC}/snow.conf ]]; then
    declare -A CLUSTERS
    source ${SNOW_ETC}/snow.conf
else
    error_msg  "The ${SNOW_ETC}/snow.conf is not available."
    error_exit "Please use the ${SNOW_ETC}/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f ${SNOW_ROOT}/share/common.sh ]]; then
    source ${SNOW_ROOT}/share/common.sh
    get_os_distro
    architecture_identification
fi

removeDebianPackage ${prefix} build-essential
removeDebianPackage ${prefix} byobu
removeDebianPackage ${prefix} bzip2
removeDebianPackage ${prefix} cpp
removeDebianPackage ${prefix} cpp-4.9
removeDebianPackage ${prefix} dash
removeDebianPackage ${prefix} dmidecode
removeDebianPackage ${prefix} fakeroot
removeDebianPackage ${prefix} g++
removeDebianPackage ${prefix} g++-4.9
removeDebianPackage ${prefix} gcc
removeDebianPackage ${prefix} gcc-4.8-base:amd64
removeDebianPackage ${prefix} gcc-4.9
removeDebianPackage ${prefix} gcc-4.9-base:amd64
removeDebianPackage ${prefix} git
removeDebianPackage ${prefix} git-man
removeDebianPackage ${prefix} gnupg
removeDebianPackage ${prefix} htop
removeDebianPackage ${prefix} iotop
removeDebianPackage ${prefix} iproute2
removeDebianPackage ${prefix} iptables
removeDebianPackage ${prefix} iptraf
removeDebianPackage ${prefix} iputils-ping
removeDebianPackage ${prefix} less
removeDebianPackage ${prefix} lsof
removeDebianPackage ${prefix} make
removeDebianPackage ${prefix} man-db
removeDebianPackage ${prefix} manpages
removeDebianPackage ${prefix} mawk
removeDebianPackage ${prefix} members
removeDebianPackage ${prefix} mime-support
removeDebianPackage ${prefix} nano
removeDebianPackage ${prefix} ncurses-base
removeDebianPackage ${prefix} ncurses-bin
removeDebianPackage ${prefix} netcat-traditional
removeDebianPackage ${prefix} parallel
removeDebianPackage ${prefix} patch
removeDebianPackage ${prefix} perl
removeDebianPackage ${prefix} perl-base
removeDebianPackage ${prefix} perl-modules
removeDebianPackage ${prefix} readline-common
removeDebianPackage ${prefix} rsyslog
removeDebianPackage ${prefix} sensible-utils
removeDebianPackage ${prefix} startpar
removeDebianPackage ${prefix} tmux
removeDebianPackage ${prefix} traceroute
removeDebianPackage ${prefix} vim
removeDebianPackage ${prefix} vim-common
removeDebianPackage ${prefix} vim-runtime
removeDebianPackage ${prefix} vim-tiny
removeDebianPackage ${prefix} wget
removeDebianPackage ${prefix} xz-utils
chroot ${prefix} /usr/bin/apt-get autoclean 
chroot ${prefix} /usr/bin/apt-get clean 
rm -fr ${prefix}/var/lib/apt/*
