#!/bin/bash
#
# This file contains recipes to deploy domains using sNow! CLI
# Copyright (C) 2008 Jordi Blasco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# sNow! Cluster Suite is an opensource project developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website: www.hpcnow.com/snow
#
#SHORT_DESCRIPTION: Installs standard HPC monitoring tools : Ganglia and Icinga.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e ${SNOW_ETC}/snow.conf ]]; then
    declare -A CLUSTERS
    source ${SNOW_ETC}/snow.conf
else
    error_msg  "The ${SNOW_ETC}/snow.conf is not available."
    error_exit "Please use the ${SNOW_ETC}/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f ${SNOW_LIB}/common.sh ]]; then
    source ${SNOW_LIB}/common.sh
    get_os_distro
    architecture_identification
fi

# Ganglia gmetad Setup 
SNOW_MONITOR_SERVER=$(gawk '{if($2 ~ /monitor/){print $4}}' $SNOW_ROOT/etc/domains.conf)
if  [[ ! -z "$SNOW_MONITOR_SERVER" && ! -z "$SITE_MONITOR_SERVER" ]]; then 
    MONITOR_SERVER=$SNOW_MONITOR_SERVER
else
    MONITOR_SERVER="${SITE_MONITOR_SERVER:-$SNOW_MONITOR_SERVER}"
fi

if  [[ ! -z "$MONITOR_SERVER" ]]; then 
    installDebianPackage ${prefix} rrdtool gmetad ganglia-webfrontend
    if [[ -e $SNOW_SRV/deploy_files/etc/ganglia-webfrontend/apache.conf ]]; then 
        cp -p $SNOW_SRV/deploy_files/etc/ganglia-webfrontend/apache.conf ${prefix}/etc/ganglia-webfrontend/apache.conf
    else
        mkdir -p $SNOW_SRV/deploy_files/etc/ganglia-webfrontend
        cp -p ${prefix}/etc/ganglia-webfrontend/apache.conf $SNOW_SRV/deploy_files/etc/ganglia-webfrontend/apache.conf 
    fi
    chroot ${prefix} /bin/ln -s /etc/ganglia-webfrontend/apache.conf /etc/apache2/sites-enabled/002-ganglia.conf
    if [[ -e $SNOW_SRV/deploy_files/etc/ganglia/gmetad.conf ]]; then 
        cp -p $SNOW_SRV/deploy_files/etc/ganglia/gmetad.conf ${prefix}/etc/ganglia/gmetad.conf
    else
        cp -p $SNOW_ROOT/etc/config_template.d/ganglia/gmetad.conf ${prefix}/etc/ganglia/gmetad.conf
        PORT=8649
        for cluster in "${!CLUSTERS[@]}" 
        do 
            replace_text ${prefix}/etc/ganglia/gmetad.conf "^#__DATA_SOURCE_COMPUTE__" "#__DATA_SOURCE_COMPUTE__\ndata_source \"${cluster}\" 60 ${SNOW_MONITOR_SERVER}:${PORT}"
            cp -p ${prefix}/etc/ganglia/gmond.conf ${prefix}/etc/ganglia/gmond_${cluster}.conf
            sed -i "s|port = .*|port = ${PORT}|g" ${prefix}/etc/ganglia/gmond_${cluster}.conf
            sed -i "s|mute = .*|mute = yes|g" ${prefix}/etc/ganglia/gmond_${cluster}.conf
            sed -i "s|deaf = .*|deaf = no|g" ${prefix}/etc/ganglia/gmond_${cluster}.conf
            sed -i 's|name = "unspecified"|name = "sNow"|g' $SNOW_SRV/deploy_files/etc/ganglia/gmond.conf
            sed -i "s|name = \"sNow Domains\"|name = \"${cluster}\"|g" ${prefix}/etc/ganglia/gmond_${cluster}.conf
            cp -p ${prefix}/etc/init.d/ganglia-monitor ${prefix}/etc/init.d/ganglia-monitor-${cluster}
            sed -i "s|ganglia-monitor|ganglia-monitor-${cluster}|g" ${prefix}/etc/init.d/ganglia-monitor-${cluster}
            sed -i "s|NAME=gmond|NAME=gmond_${cluster}|g" ${prefix}/etc/init.d/ganglia-monitor-${cluster}
            sed -i 's|$DAEMON --|$DAEMON -- -c /etc/ganglia/${NAME}.conf|g' ${prefix}/etc/init.d/ganglia-monitor-${cluster}
            sed -i 's|--oknodo --name $NAME|--oknodo --pidfile /var/run/$NAME.pid|g' ${prefix}/etc/init.d/ganglia-monitor-${cluster}
            chroot ${prefix} /usr/sbin/update-rc.d ganglia-monitor-${cluster} defaults
            PORT=$((PORT-=1))
            cp -p ${prefix}/etc/ganglia/gmond_${cluster}.conf $SNOW_SRV/deploy_files/etc/ganglia/gmond_${cluster}.conf
            sed -i "s|mute = .*|mute = no|g" $SNOW_SRV/deploy_files/etc/ganglia/gmond_${cluster}.conf
            sed -i "s|deaf = .*|deaf = yes|g" $SNOW_SRV/deploy_files/etc/ganglia/gmond_${cluster}.conf
        done
        unset PORT
        replace_text ${prefix}/etc/ganglia/gmetad.conf "^#__DATA_SOURCE_DOMAINS__" "data_source \"sNow Domains\" 60 $SNOW_MONITOR_SERVER:8650"
        mkdir -p $SNOW_SRV/deploy_files/etc/ganglia/
        cp -p ${prefix}/etc/ganglia/gmetad.conf $SNOW_SRV/deploy_files/etc/ganglia/gmetad.conf
        cp -p ${prefix}/etc/ganglia/gmond.conf ${prefix}/etc/ganglia/gmond_domains.conf
        sed -i "s|mute = .*|mute = no|g" ${prefix}/etc/ganglia/gmond_domains.conf
        sed -i "s|deaf = .*|deaf = no|g" ${prefix}/etc/ganglia/gmond_domains.conf
        cp -p ${prefix}/etc/init.d/ganglia-monitor ${prefix}/etc/init.d/ganglia-monitor-domains
        sed -i "s|ganglia-monitor|ganglia-monitor-domains|g" ${prefix}/etc/init.d/ganglia-monitor-domains
        sed -i "s|NAME=gmond|NAME=gmond_domains|g" ${prefix}/etc/init.d/ganglia-monitor-domains
        sed -i 's|$DAEMON --|$DAEMON -- -c /etc/ganglia/${NAME}.conf|g' ${prefix}/etc/init.d/ganglia-monitor-domains
        sed -i 's|--oknodo --name $NAME|--oknodo --pidfile /var/run/$NAME.pid|g' ${prefix}/etc/init.d/ganglia-monitor-domains
        chroot ${prefix} /usr/sbin/update-rc.d ganglia-monitor remove
        chroot ${prefix} /bin/chmod -x /etc/init.d/ganglia-monitor
        chroot ${prefix} /usr/sbin/update-rc.d ganglia-monitor-domains defaults
    fi
fi
