#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#
#SHORT_DESCRIPTION: Installs standard HPC monitoring tools : Ganglia and Icinga.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    declare -A CLUSTERS
    source /sNow/snow-tools/etc/snow.conf
else
    error_msg  "The /sNow/snow-tools/etc/snow.conf is not available."
    error_exit "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f /sNow/snow-tools/share/common.sh ]]; then
    source /sNow/snow-tools/share/common.sh
    get_os_distro
    architecture_identification
fi

# Ganglia gmetad Setup 
SNOW_MONITOR_SERVER=$(gawk '{if($2 ~ /monitor/){print $4}}' $SNOW_TOOL/etc/domains.conf)
if  [[ ! -z "$SNOW_MONITOR_SERVER" && ! -z "$SITE_MONITOR_SERVER" ]]; then 
    MONITOR_SERVER=$SNOW_MONITOR_SERVER
else
    MONITOR_SERVER="${SITE_MONITOR_SERVER:-$SNOW_MONITOR_SERVER}"
fi

if  [[ ! -z "$MONITOR_SERVER" ]]; then 
    installDebianPackage ${prefix} rrdtool gmetad ganglia-webfrontend
    if [[ -e $SNOW_CONF/system_files/etc/ganglia-webfrontend/apache.conf ]]; then 
        cp -p $SNOW_CONF/system_files/etc/ganglia-webfrontend/apache.conf ${prefix}/etc/ganglia-webfrontend/apache.conf
    else
        mkdir -p $SNOW_CONF/system_files/etc/ganglia-webfrontend
        cp -p ${prefix}/etc/ganglia-webfrontend/apache.conf $SNOW_CONF/system_files/etc/ganglia-webfrontend/apache.conf 
    fi
    chroot ${prefix} /bin/ln -s /etc/ganglia-webfrontend/apache.conf /etc/apache2/sites-enabled/002-ganglia.conf
    if [[ -e $SNOW_CONF/system_files/etc/ganglia/gmetad.conf ]]; then 
        cp -p $SNOW_CONF/system_files/etc/ganglia/gmetad.conf ${prefix}/etc/ganglia/gmetad.conf
    else
        cp -p $SNOW_TOOL/etc/config_template.d/ganglia/gmetad.conf ${prefix}/etc/ganglia/gmetad.conf
        for cluster in "${!CLUSTERS[@]}" 
        do 
            nodelist=${CLUSTERS[$cluster]}
            aggregators=$(node_list "${nodelist}" | gawk '{print $1" "$2}')
            replace_text ${prefix}/etc/ganglia/gmetad.conf "^#__DATA_SOURCE_COMPUTE__" "#__DATA_SOURCE_COMPUTE__\ndata_source $cluster 60 $aggregators"
            unset nodelist
            unset aggregators
        done
        replace_text ${prefix}/etc/ganglia/gmetad.conf "^#__DATA_SOURCE_DOMAINS__" "data_source \"sNow Domains\" 60 $SNOW_MONITOR_SERVER"
        mkdir -p $SNOW_CONF/system_files/etc/ganglia/
        cp -p ${prefix}/etc/ganglia/gmetad.conf $SNOW_CONF/system_files/etc/ganglia/gmetad.conf
    fi
fi
