#!/bin/bash
#
# This file contains recipes to deploy domains using sNow! CLI
# Copyright (C) 2008 Jordi Blasco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# sNow! Cluster Suite is an opensource project developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website: www.hpcnow.com/snow
#
#SHORT_DESCRIPTION: Installs OpenVPN Access Server (2 free client connections for testing purposes).
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e ${SNOW_ETC}/snow.conf ]]; then
    declare -A CLUSTERS
    source ${SNOW_ETC}/snow.conf
else
    error_msg  "The ${SNOW_ETC}/snow.conf is not available."
    error_exit "Please use the ${SNOW_ETC}/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f ${SNOW_LIB}/common.sh ]]; then
    source ${SNOW_LIB}/common.sh
    get_os_distro
    architecture_identification
fi

# Download the OpenVPN AS package
wget http://swupdate.openvpn.org/as/openvpn-as-2.0.25-Debian8.amd_64.deb -O ${prefix}/root/openvpn-as-2.0.25-Debian8.amd_64.deb

# Stage domain entrypoint script
cp -p $SNOW_ROOT/etc/role.d/first_boot/openvpn_as.sh  ${prefix}/usr/local/first_boot/openvpn_as.sh
sed -i "s|__MASTER_PASSWORD__|$MASTER_PASSWORD|g" ${prefix}/usr/local/first_boot/openvpn_as.sh

# Domain Setup
if [[ -d ${SNOW_SRV}/deploy_files/etc/openvpn_as ]]; then
    cp -pr ${SNOW_SRV}/deploy_files/etc/openvpn_as ${prefix}/usr/local/openvpn_as/etc
    sed -i "s|__OPENVPNAS_RECONFIGURE__|false|g" ${prefix}/usr/local/first_boot/openvpn_as.sh
else
    mkdir -p ${SNOW_SRV}/deploy_files/etc/openvpn_as
    sed -i "s|__OPENVPNAS_RECONFIGURE__|true|g" ${prefix}/usr/local/first_boot/openvpn_as.sh
fi
