#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#

set -xv

prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    . /sNow/snow-tools/etc/snow.conf
else
    echo "The /sNow/snow-tools/etc/snow.conf is not available."
    echo "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive

# Slurm Database Server Setup
SNOW_SLURMDBD_SERVER=$(gawk '{if($2 ~ /slurmdbd/){print $1}}' $SNOW_TOOL/etc/domains.conf)
if  [[ ! -z "$SNOW_SLURMDBD_SERVER" ]]; then 
    #chroot ${prefix} /usr/bin/apt-get update -q 
    echo "mysql-server-5.5 mysql-server/root_password password $MASTERPWD" | chroot ${prefix} /usr/bin/debconf-set-selections
    echo "mysql-server-5.5 mysql-server/root_password_again password $MASTERPWD" | chroot ${prefix} /usr/bin/debconf-set-selections
    #MASTERPWD=HPCNow
    DEBIAN_FRONTEND=noninteractive chroot ${prefix} /usr/bin/apt-get install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" curl pbzip2 mysql-server
    #installDebianPackage ${prefix} curl pbzip2 mysql-server
    #chroot ${prefix} /usr/bin/mysqladmin -u root password '$MASTERPWD'
    chroot ${prefix} /bin/systemctl start mysql.service
    chroot ${prefix} /bin/systemctl enable mysql.service
    echo "create database $MYSQL_DATABASE;" | chroot ${prefix} /usr/bin/mysql -u root -p $MASTERPWD
    echo "grant all on $MYSQL_DATABASE.* to $SLURMDBD_USER@localhost identified by '$SLURMDBD_PWD';" | chroot ${prefix} /usr/bin/mysql -u root -p $MASTERPWD
    chroot ${prefix} /bin/systemctl stop mysql.service
    #/usr/bin/curl -sSL http://repo.hpcnow.com/apt/gpg.key | chroot ${prefix} /usr/bin/apt-key add - 
    /usr/bin/curl -sSL http://packages.nesi.org.nz/nesi.gpg.key | chroot ${prefix} /usr/bin/apt-key add - 
    #echo "deb http://repo.hpcnow.com/apt/debian jessie main" > ${prefix}/etc/apt/sources.list.d/snow.list 
    echo "deb http://packages.nesi.org.nz/slurm-debian/apt/debian jessie main" > ${prefix}/etc/apt/sources.list.d/snow.list 
    chroot ${prefix} /usr/bin/apt-get update -q 
    installDebianPackage ${prefix} slurm-llnl-slurmdbd slurm-client 
    sed -i 's/slurm-llnl/slurm/g' ${prefix}/etc/init.d/slurm* 
    chroot ${prefix} /bin/ln -s /usr/bin/mail /bin/mail 
    # Check UIDs and GIDs
    if [[ "$(chroot ${prefix} id -u munge)" != "$MUNGE_UID"  &&  "$(chroot ${prefix} id -g munge)" != "$MUNGE_GID" ]]; then
        chroot ${prefix} /usr/sbin/groupmod -g $MUNGE_GID munge
        chroot ${prefix} /usr/sbin/usermod -u $MUNGE_UID -g $MUNGE_GID munge
    fi
    if [[ "$(chroot ${prefix} id -u slurm)" != "$SLURM_UID"  &&  "$(chroot ${prefix} id -g slurm)" != "$SLURM_GID" ]]; then
        chroot ${prefix} /usr/sbin/groupmod -g $SLURM_GID slurm
        chroot ${prefix} /usr/sbin/usermod -u $SLURM_UID -g $SLURM_GID slurm
    fi
    # Setup Munge key slurm
    # Note that if you alredy have the config files available, no changes will be performed.
    if [[ ! -e $SNOW_CONF/system_files/etc/munge/munge.key ]]; then
        dd if=/dev/urandom bs=1 count=1024 > ${prefix}/etc/munge/munge.key 
        chroot ${prefix} /bin/mkdir -p /var/log/munge /var/lib/munge /etc/munge /var/run/munge
        chroot ${prefix} /bin/chown -R munge:munge /var/log/munge /var/lib/munge /etc/munge /var/run/munge
        chroot ${prefix} /bin/chmod 700 /etc/munge
        chroot ${prefix} /bin/chmod 600 /etc/munge/munge.key 
    fi
    if [[ -e $SNOW_CONF/system_files/etc/slurm/slurmdbd.conf ]]; then 
        # The current configuration located in $SNOW_CONF/system_files/etc/slurm 
        # will be used for this sNow! domain.
        chroot ${prefix} /bin/mkdir -p /etc/slurm /var/run/slurm /var/spool/slurmd /var/spool/slurm /var/log/slurm
        cp -pr $SNOW_CONF/system_files/etc/slurm ${prefix}/etc/
    else
        # Setup initial Slurm Database configuration based on the environment.
        # Note that if you alredy have the config files available, no changes will be performed.
        chroot ${prefix} /bin/mkdir -p /etc/slurm /var/run/slurm /var/spool/slurmd /var/spool/slurm /var/log/slurm
        cp -pr $SNOW_TOOL/etc/config_template.d/slurmdbd/slurmdbd.conf ${prefix}/etc/slurm/
        sed -i "s/__SLURMDBD_PWD__/$SLURMDBD_PWD/g" ${prefix}/etc/slurm/slurmdbd.conf
        sed -i "s/__SLURMDBD_USER__/$SLURMDBD_USER/g" ${prefix}/etc/slurm/slurmdbd.conf
        cp -p ${prefix}/etc/slurm/slurmdbd.conf $SNOW_CONF/system_files/etc/slurm/slurmdbd.conf
    fi
    chroot ${prefix} /bin/chown -R slurm:slurm /etc/slurm /var/spool/slurmd /var/spool/slurm /var/log/slurm
    echo "export SLURM_CONF=/etc/slurm/slurmdbd.conf" >> /etc/default/slurm
fi

