#!/bin/sh
# Configure the new image for sNow! HPC suite
# Developed by NPCNow! www.hpcnow.com
# Jordi Blasco
#

prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi


#  Update APT lists.
#chroot ${prefix} /usr/bin/apt-get update
# LDAP Install references : 
# https://wiki.debian.org/LDAP/OpenLDAPSetup
# http://www.server-world.info/en/note?os=Debian_8&p=openldap
# http://www.server-world.info/en/note?os=Debian_8&p=ssl
# SSSD client
# https://wiki.ubuntu.com/Enterprise/Authentication/sssd
#installDebianPackage ${prefix} libnss-ldap libpam-ldap nscd sssd-ldap
installDebianPackage ${prefix} libpam-ldap sssd-ldap sssd-tools sssd-common

#  Install the packages
installDebianPackage ${prefix} dpkg-dev
installDebianPackage ${prefix} devscripts
installDebianPackage ${prefix} fakeroot
installDebianPackage ${prefix} debhelper
installDebianPackage ${prefix} build-essential
chroot ${prefix} /usr/bin/delgroup scanner  
installDebianPackage ${prefix} colord build-essential automake autoconf libtool pkg-config libcurl4-openssl-dev intltool libxml2-dev libgtk2.0-dev libnotify-dev libglib2.0-dev libevent-dev checkinstall
installDebianPackage ${prefix} libmunge-dev libmunge2 munge
installDebianPackage ${prefix} build-essential ncurses-base ncurses-bin ncurses-doc libncurses5-dev libgtk2.0-0 libgtk2.0-dev rrdtool librrd-dev libcgroup1 libcgroup-dev hwloc libhwloc-dev lua5.2 liblua5.2-dev liblua5.2-0 linux-kernel-headers libreadline-dev libssl-dev libpam-dev numactl libnuma-dev freeipmi libhdf5-8 libhdf5-dev hdf5-tools pdsh
