#!/bin/sh
# Configure the new image for sNow! HPC suite
# Developed by HPCNow! www.hpcnow.com
# Jordi Blasco
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi


chroot ${prefix} /usr/bin/apt-get update
installDebianPackage ${prefix} dpkg-dev devscripts fakeroot debhelper build-essential htop byobu gawk git iotop lsof traceroute iptraf vim colord
# Minor fixes related with colord uid and gid bug
chroot ${prefix} /usr/sbin/groupmod -g 119 colord
chroot ${prefix} /usr/sbin/groupmod -g 1000 snow
chroot ${prefix} /usr/sbin/usermod -u 1000 -g 1000 snow
chroot ${prefix} /usr/sbin/addgroup --gid 109 Debian-exim --force-badname
