#!/bin/bash
#
# This file contains recipes to deploy domains using sNow! CLI
# Copyright (C) 2008 Jordi Blasco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# sNow! Cluster Suite is an opensource project developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website: www.hpcnow.com/snow
#
#SHORT_DESCRIPTION: Installs a centralised Rsyslog server to consolidate the logs of the whole cluster.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e ${SNOW_ETC}/snow.conf ]]; then
    declare -A CLUSTERS
    source ${SNOW_ETC}/snow.conf
else
    error_msg  "The ${SNOW_ETC}/snow.conf is not available."
    error_exit "Please use the ${SNOW_ETC}/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f ${SNOW_ROOT}/share/common.sh ]]; then
    source ${SNOW_ROOT}/share/common.sh
    get_os_distro
    architecture_identification
fi

# Rsyslog Server Setup
SNOW_SYSLOG_SERVER=$(gawk '{if($2 ~ /syslog/){print $4}}' $SNOW_ROOT/etc/domains.conf)
if  [[ ! -z "$SNOW_SYSLOG_SERVER" ]]; then 
    installDebianPackage ${prefix} rsyslog
    if [[ -e ${SNOW_SRV}/deploy_files/etc/rsyslog.conf ]]; then 
        cp -p ${SNOW_SRV}/deploy_files/etc/rsyslog.conf ${prefix}/etc/rsyslog.conf
    else
        mkdir -p ${SNOW_SRV}/deploy_files/etc/
        sed -i 's|#$ModLoad imtcp|$ModLoad imtcp|g' ${prefix}/etc/rsyslog.conf 
        sed -i 's|#$InputTCPServerRun 514|$InputTCPServerRun 514|g' ${prefix}/etc/rsyslog.conf 
        cp -p ${prefix}/etc/rsyslog.conf ${SNOW_SRV}/deploy_files/etc/rsyslog.conf
    fi
    rm ${prefix}/etc/rsyslog.d/50-default.conf
fi

