#!/bin/bash
# Configure the new image for sNow! HPC suite
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
#
# Based on Steve Kemp's role: http://www.steve.org.uk/
#
#SHORT_DESCRIPTION: Installs XDM with VNC support.
prefix=$1

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    source /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e /sNow/snow-tools/etc/snow.conf ]]; then
    declare -A CLUSTERS
    source /sNow/snow-tools/etc/snow.conf
else
    error_msg  "The /sNow/snow-tools/etc/snow.conf is not available."
    error_exit "Please use the /sNow/snow-tools/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f /sNow/snow-tools/share/common.sh ]]; then
    source /sNow/snow-tools/share/common.sh
    get_os_distro
    architecture_identification
fi

#  Update APT lists.
chroot ${prefix} /usr/bin/apt-get update

#  Install the packages
installDebianPackage ${prefix} xserver-xorg
installDebianPackage ${prefix} vnc4server
installDebianPackage ${prefix} xfonts-100dpi
installDebianPackage ${prefix} xfonts-75dpi
installDebianPackage ${prefix} xfonts-base
installDebianPackage ${prefix} rxvt
installDebianPackage ${prefix} xdm
installDebianPackage ${prefix} lxde-core

#  Remove the default settings.
rm ${prefix}/etc/X11/xdm/Xserver
rm ${prefix}/etc/X11/xdm/Xservers

#  Setup XDM to use the VNC server we installed.
/bin/echo ':0 /usr/bin/Xvnc /usr/bin/Xvnc -geometry 1024x768 -depth 24' > ${prefix}/etc/X11/xdm/Xservers
