#!/bin/bash
#set -xv
# sNow! paths
# SNOW_HOME and SNOW_SOFT can be setup in different paths
SNOW_PATH=/sNow
SNOW_CONF=$SNOW_PATH/snow-configspace
SNOW_TOOL=$SNOW_PATH/snow-tools
LOGFILE=/root/first-boot.log
RETAIN_NUM_LINES=10
TEMPLATE_PATH=${SNOW_CONF}/boot/templates/__DEFAULT_TEMPLATE__

#  Source our common functions - this will let us install a Debian package.
if [[ -e /usr/share/xen-tools/common.sh ]]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi
# Load sNow! configuration
if [[ -e ${SNOW_TOOL}/etc/snow.conf ]]; then
    source ${SNOW_TOOL}/etc/snow.conf
else
    error_msg  "The ${SNOW_TOOL}/etc/snow.conf is not available."
    error_exit "Please use the ${SNOW_TOOL}/etc/snow.conf-example to setup your environment."
fi
# Load sNow! functions
if [[ -f ${SNOW_TOOL}/share/common.sh ]]; then
    source ${SNOW_TOOL}/share/common.sh
    logsetup
    get_os_distro
    architecture_identification
fi

if [[ -f ${TEMPLATE_PATH}/config ]]; then
    echo "Loading __DEFAULT_TEMPLATE__ configuration ..."
    source ${TEMPLATE_PATH}/config
else
    echo "Config file not found"
fi

case "$1" in
  start)
    hooks ${TEMPLATE_PATH}/first_boot/ 
    systemctl disable first_boot
	;;
  stop)
    systemctl disable first_boot
	;;
  *)
	log_action_msg "Usage: systemctl {start|stop} first_boot" || true
	exit 1
esac

exit 0
