#!/usr/bin/gawk -f 
# fishermac allows you to capture the mac addresses from the dnsmasq leases file
# This script is part of sNow! Command Line Interface 
# Developed by Jordi Blasco <jordi.blasco@hpcnow.com>
# For more information, visit the official website : www.hpcnow.com/snow
{
    timestamp=$1
    mac=$2
    ip=$3
    host=$4
    print mac"  "ip
}
