#! /bin/sh
set -e

case "$1" in
  start)
    cf-agent --bootstrap __CF_MASTER__
    systemctl disable cf_boot
	;;
  stop)
    systemctl disable cf_boot
	;;
  *)
	log_action_msg "Usage: systemctl {start|stop} cf_boot" || true
	exit 1
esac

exit 0
